import type { Metadata } from "next"
import "../styles/globals.css"
import "../styles/scss/main.scss"
import { ContextProvider } from "@/components/modules/contextProvider"

export const metadata: Metadata = {
  title: "Crypto®",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  )
}
